services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Esta porta é default
    volumes:
      - mongo_data:/data/db
    networks:
      - ualflix_net

  catalog:
    build: ./catalog-service
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/ualflix
    networks:
      - ualflix_net

  streaming:
    build: ./streaming-service
    ports:
      - "5002:5000"
    networks:
      - ualflix_net

  upload:
    build: ./upload-service
    ports:
      - "5003:5000"
    volumes:
      - ./upload-service/uploads_data:/app/uploads_data
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/ualflix
    networks:
      - ualflix_net

  admin:
    build: ./admin-service
    ports:
      - "5004:5000"
    depends_on:
      - catalog
    networks:
      - ualflix_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./upload-service/uploads_data/videos:/srv/videos_public:ro
    depends_on:
      - catalog
      - streaming
      - upload
      - admin
    networks:
      - ualflix_net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_CATALOG_API_URL=http://localhost/api/catalog
      - NEXT_PUBLIC_ADMIN_API_URL=http://localhost/api/admin
      - NEXT_PUBLIC_UPLOAD_API_URL=http://localhost/api/upload
    depends_on:
      - nginx
    networks:
      - ualflix_net

volumes:
  upload_data:
  mongo_data:

networks:
  ualflix_net:
    driver: bridge
