version: "3.9"
services:
  catalog:
    build: ./catalog-service
    ports:
      - "5001:5000"
  streaming:
    build: ./streaming-service
    ports:
      - "5002:5000"
  upload:
    build: ./upload-service
    ports:
      - "5003:5000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf