global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "catalog-service"
    static_configs:
      - targets: ["catalog-service:5000"]
  - job_name: "admin-service"
    static_configs:
      - targets: ["admin-service:5000"]
  - job_name: "upload-service"
    static_configs:
      - targets: ["upload-service:5000"]
  - job_name: "streaming-service"
    static_configs:
      - targets: ["streaming-service:5000"]
