apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin
          image: iulian169/ualflix-admin:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service:5000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
