apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      volumes:
        - name: upload-storage
          persistentVolumeClaim:
            claimName: upload-pvc
      containers:
        - name: catalog
          image: iulian169/ualflix-catalog:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/ualflix?replicaSet=ualflix-rs"
            - name: REDIS_HOST
              value: "redis-service"
          volumeMounts:
            - mountPath: /app/uploads_data
              name: upload-storage
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
