apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-service
  labels:
    app: streaming-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streaming-service
  template:
    metadata:
      labels:
        app: streaming-service
    spec:
      volumes:
        - name: upload-storage
          persistentVolumeClaim:
            claimName: upload-pvc
      containers:
        - name: streaming
          image: iulian169/ualflix-streaming:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: upload-storage
              mountPath: /app/uploads_data
              readOnly: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-service
spec:
  selector:
    app: streaming-service
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
