apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
  labels:
    app: upload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-service
  template:
    metadata:
      labels:
        app: upload-service
    spec:
      volumes:
        - name: upload-storage
          persistentVolumeClaim:
            claimName: upload-pvc
      containers:
        - name: upload
          image: iulian169/ualflix-upload:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service:5000/videos"
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/ualflix?replicaSet=ualflix-rs"
          volumeMounts:
            - name: upload-storage
              mountPath: /app/uploads_data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
spec:
  selector:
    app: upload-service
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
